# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3146370537505f7161874d9320a6bce1e0683f5af95ce7ec1350a261184003d985cb1d79a5cadf186c11071d6c576fd83e2c5ebeddbfedadab99a47d23716942

test:
  secret_key_base: 3c6eb6141d14d39eab08a714ba704f6a954a4fc48e0f5f59cb0f5ec24b4b27c3c43600f1bac2e23f5527af794df1793813b67c56d6f91390b19636dd2a367afe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
